config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  post 'email_form' => 'pages#email_form'
  resources :ads, only: [:create,:edit,:update, :destroy] do 
    get :update_page, on: :member
  end

end

app/models/ad.rb
class Ad < ActiveRecord::Base
    mount_uploader :house_image, HouseImageUploader
    mount_uploader :profile_image, ProfileImageUploader
    
    def city_state
        if zipcode =~/^\d{5}(-\d{4})?$/
            zc=ZipCodes.identify(zipcode)
            if !zc.blank?
                return zc[:city] + ", " + zc[:state_code]
            end
        end
        return zipcode
    end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  def create
    @ad = Ad.new(ad_params)
    respond_to do |format|
      if @ad.save
        format.html { redirect_to root_url }
        format.js {
          @ad = Ad.new(
            design: 1,
            name: "Enter your name here", 
            company: "Enter your company here",
            phone_number: "111-222-3333",
            zipcode: "12345",
            text_1: "Enter text here",
            text_2: "Enter more text here")
          @ads = Ad.order('created_at desc').paginate(:page => params[:page], per_page: 10)
          render :update_page
        }
      else
        format.html { render root_url }
        format.js { render :update_page }
      end
    end
  end
  
  def edit
    @ad = Ad.find(params[:id])
    @ads = Ad.all.paginate(:page => params[:page])
    
    respond_to do |format|
      format.html { render "/pages/home"}
      format.js
    end
  end
  
  def update
    @ad = Ad.find(params[:id])
    respond_to do |format|
      if @ad.update_attributes(ad_params)
        format.html { redirect_to root_url }
        format.js { 
          @ad =Ad.new(design: 1)
          @ads = Ad.all.paginate(:page => params[:page])
          render :update_page
          
        }
      else
        format.html { render root_url }
        format.js { render :update_page }
      end
    end
  end
  
  
  def destroy
    @ad = Ad.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to root_url}
      format.js
    end
  end
  
  private
     # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:name, :company,:phone_number,:zipcode,:profile_image,:house_image,:text_1,:text_2,:background_color_1,:text_color_1,:background_color_2,:text_color_2,:design)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  skip_before_filter :verify_authenticity_token  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Ad Generator"
    @ad = Ad.new(
      design: 1,
      name: "Enter your name here", 
      company: "Enter your company here",
      phone_number: "111-222-3333",
      zipcode: "12345",
      text_1: "Enter text here",
      text_2: "Enter more text here")
    @ads = Ad.order('created_at desc').paginate(:page => params[:page], per_page: 10)
  end
  
  def email_form
    @name = params[:name]
    @email = params[:email]
    @question = params[:question]
    HelpMailer.help_form(@name,@email,@question).deliver_now
    flash[:info] = "Please check your email to activate your account."
    respond_to do |format|
      format.html {redirect_to root_url}
      format.js
    end
  end
  
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ads/_ad.html.erb
<div style="float:left;margin:10px" id="ad_model-<%= ad.id %>">
    <%= render "pages/design_#{ad.design}", ad: ad %>
    <p style="text-align:center"><%= link_to "Edit", edit_ad_path(ad), remote: true %> | <%= link_to 'Delete', ad_path(ad), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></p>
</div>

app/views/ads/destroy.js.erb
$('#ad_model-<%= @ad.id %>').fadeOut()

app/views/ads/edit.js.erb
$('#form').html('<%=j render 'pages/form', ad: @ad %>')
$('#preview').html('<%=j render "pages/preview" %>')
$('.fill').find('img').each(function(){
    var imgClass = (this.width/this.height > $(this).parent().width()/$(this).parent().height()) ? 'wide' : 'tall';
    $(this).addClass(imgClass);
})
window.scrollTo(0,0);

app/views/ads/update_page.js.erb
$('#form').html('<%=j render 'pages/form', ad: @ad %>')
$('#preview').html('<%=j render "pages/preview" %>')
$('#list').html('<%=j render "pages/list" %>')
window.pageReady()

window.scrollTo(0,0);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%=favicon_link_tag('favicon.png') %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width; initial-scale=1.0;" />
</head>
<body>
<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/pages/_design_1.html.erb
<div class="design design-1">
  <div class="section-1 toptext" style="background:<%= ad.background_color_1 %>;color:<%= ad.text_color_1 %>;">
    <p><span class="text_1"><%= ad.text_1 %></span></p>
  </div>
  <div class="fill">
    <%= image_tag ad.house_image.blank? ? "house.png" : ad.house_image, class: "house" %>
    <div class="callbox">
      Click or Call <span class="phone-number"><%= ad.phone_number %></span>
    </div>
  </div>
  <div class="section-1 middletext" style="background:<%= ad.background_color_1 %>;color:<%= ad.text_color_1 %>;">
    <div class="namecompany">
      <span class="name"><%= ad.name %></span><br>
      <span class="company"><%= ad.company %></span>
    </div>
  </div>
  <div class="section-2" style="background:<%= ad.background_color_2 %>;color:<%= ad.text_color_2 %>;">
    <div class="zip">
      <span class="zipcode"><%= ad.city_state %></span>
    </div>
  </div>
  <div class="profile-container fill">
    <%= image_tag (ad.profile_image.blank? ? "profile.png" : ad.profile_image), class: "profile" %>
  </div>
</div>

app/views/pages/_design_2.html.erb
<div class="design-2">
  <div class="section-1" style="background:<%= ad.background_color_1 %>;color:<%= ad.text_color_1 %>;">
    <p class="name"><%= ad.name %></p>
    <p class="text_1"><%= ad.text_1 %></p>
  </div>
  <div class="middle">
    <div class="profile-container fill">
        <%= image_tag (ad.profile_image.blank? ? "profile.png" : ad.profile_image), class: "profile" %>
    </div>
    <div class="section-2" style="background:<%= ad.background_color_2 %>;color:<%= ad.text_color_2 %>;">
      <span class="text_2"><%= ad.text_2 %></span>
      <div class="number-button" style="border-color: <%= ad.text_color_2 %>;">
          <span class="phone-number"><%= ad.phone_number %></span>
      </div>
    </div>
  </div>
  <div class="section-3" style="color:<%= ad.background_color_2 %>;">
     <%= image_tag (ad.house_image.blank? ? "house.png" : ad.house_image), class: "house" %>
     <span class="company"><%= ad.company %></span><br><span class="zipcode"><%= ad.city_state %></span>
  </div>
</div>

app/views/pages/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/pages/_form.html.erb
<h2>Enter Your Information:</h2>
<%= form_for ad, html: { multipart: true, remote: true, class: "form-horizontal" } do |f| %>
  <%= render 'pages/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :design, "Ad design", class: "control-label col-sm-3" %>
    <div class="col-sm-9">
      <%= f.select :design, [['Design 1', 1],['Design 2', 2]], {}, {class: "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "control-label col-sm-3" %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: "form-control", data: {target: ".name"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company, class: "control-label col-sm-3" %>
    <div class="col-sm-9">
      <%= f.text_field :company, class: "form-control", data: {target: ".company"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, class: "control-label col-sm-3" %>
    <div class="col-sm-9">
      <%= f.text_field :phone_number, class: "form-control", data: {target: ".phone-number"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zipcode, class: "control-label col-sm-3" %>
    <div class="col-sm-9">
      <%= f.text_field :zipcode, class: "form-control", data: {target: ".zipcode"} %>
    </div>
  </div>
  <div class= "form-group">
    <%= f.label :profile_image, class: "control-label col-sm-3" %>
    <div class="col-sm-9">
      <%= f.file_field :profile_image, data: {target: ".profile"} %>
    </div>
  </div>
  <div class= "form-group">
    <%= f.label :house_image, class: "control-label col-sm-3" %>
    <div class="col-sm-9">
      <%= f.file_field :house_image, data: {target: ".house"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :text_1, class: "control-label col-sm-3" %>
    <div class="col-sm-9">
      <%= f.text_field :text_1, class: "form-control", data: {target: ".text_1"} %>
    </div>
  </div>
  <div class="form-group" id="text_2_group">
    <%= f.label :text_2, class: "control-label col-sm-3" %>
    <div class="col-sm-9">
      <%= f.text_field :text_2, class: "form-control", data: {target: ".text_2"} %>
    </div>
  </div>
  <div class="form-group">
    <strong class= "control-label col-sm-3">Section 1</strong>
    <div class="col-sm-4 colorpicker-input" data-target-attribute="background-color" data-target-class="section-1">
      <%= f.label :background_color_1, "Background" %>
      <%= f.hidden_field :background_color_1, class: "form-control"%><span class="input-group-addon"><i></i></span>
    </div>
    <div class="col-sm-offset-1 col-sm-4 colorpicker-input" data-target-attribute="color" data-target-class="section-1">
      <%= f.label :text_color_1, "Text" %>
      <%= f.hidden_field :text_color_1, class: "form-control"%><span class="input-group-addon"><i></i></span>
    </div>
  </div>
  <div class="form-group">
    <strong class= "control-label col-sm-3">Section 2</strong>
    <div class="col-sm-4 colorpicker-input" data-target-attribute="background-color" data-target-class="section-2">
      <%= f.label :background_color_2, "Background" %>
      <%= f.hidden_field :background_color_2, class: "form-control"%><span class="input-group-addon"><i></i></span>
    </div>
    <div class="col-sm-offset-1 col-sm-4 colorpicker-input" data-target-attribute="color" data-target-class="section-2">
      <%= f.label :text_color_2, "Text" %>
      <%= f.hidden_field :text_color_2, class: "form-control"%><span class="input-group-addon"><i></i></span>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-10">
      <%= f.submit ad.new_record? ? "Save Ad" : "Update Ad", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>


<script>
$(function(){
  if ($('#ad_design').val() == 1) {
    $('#text_2_group').hide()
  } else {
    $('#text_2_group').show()
  }
  $('#ad_design').change(function () {
    if ($(this).val() == 1) {
      $('#design').html("<%=j render 'pages/design_1', ad: @ad %>")
      $('#text_2_group').hide()
    } else {
      $('#design').html("<%=j render 'pages/design_2', ad: @ad %>")
      $('#text_2_group').show()
    }
    $.each($('.form-group input[type="text"]'), function(key,value) { 
      $('#preview ' + $(value).data('target')).text($(value).val());
    })
    $.each($('.colorpicker-input'), function(key,value) { 
      $('#preview .' + $(value).data("target-class")).css($(value).data("target-attribute"),$(value).find('.form-control').val());
    })
    $.each($("input[type='file']"), function(key,value) { 
      window.readURL(value);
    })
    window.pageReady()
  });
});
</script>

app/views/pages/_list.html.erb
<div class="col-xs-12">
    <%= will_paginate @ads, renderer: BootstrapPagination::Rails %>
</div>
<%= render @ads %>
<div class="col-xs-12"><%= will_paginate @ads, renderer: BootstrapPagination::Rails %></div>

app/views/pages/_preview.html.erb
<h2>Preview:</h2><span id="design"><%= render "pages/design_#{@ad.design}", ad: @ad %></span>

app/views/pages/email_form.js.erb
$("#myModal").modal("hide")
$("#thanksModal").modal("show")
$("#myModal input[type='text']").val("")
$("#myModal textarea").val("")

app/views/pages/home.html.erb
<div class="affix-background affix"></div>
<div class="affix-foreground affix">
  <%= image_tag "help_pic.jpg", id: "helpimg" %>
  <div class="popover bottom">
      <div class="arrow"></div>
      <p class="popover-title"><small></small>Need help?</p>
      <div class="popover-content"><small>Email Support!</small> 
      </div> 
     </div>
</div> 
<h1>Ad Generator</h1>
<div class="row">
    <div id="form" class="col-sm-6"><%= render 'pages/form', ad: @ad %></div>
    <div id="preview" class="col-sm-6"><%= render 'pages/preview' %></div>
</div>
<h2>Past Designs</h2>
<div id="list" class="row">
    <%= render "pages/list" %>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Let us help you!</h4>
      </div>
      <div class="modal-body">
        <%= form_tag email_form_path, class: "form-horizontal", remote: true do %>

        <div class="form-group">
            <%= label_tag :name, "Name", class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= text_field_tag :name, "", class: "form-control" %>
            </div>
        </div>
        <div class="form-group">
            <%= label_tag :email, "Email", class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= text_field_tag :email, "", class: "form-control" %>
            </div>
        </div>
        <div class="form-group">
            <%= label_tag :question, "Question", class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= text_area_tag :question, "", class: "form-control" %>
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Chat with us", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="thanksModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Thanks!</h4>
      </div>
      <div class="modal-body">
        <p>Thanks for your feedback! Someone will be contacting you shortly.</p>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>